version: "3.9"
services:
   backend-challenge:
    image: backend-challenge
    container_name: backend-challenge
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        PHP_VERSION: '8.2.4-fpm-bullseye'
    ports:
      - "9000:80" #http
      - "443:443" #https
